---
id: Translation
name: Translation
full: Translation library
description: A translation wrappers library.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Translation
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 3.0.0alpha3
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
  optional:
    composer:
      horde/test: ^3
    ext:
      gettext: '*'
